//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliqueDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueTagRequest
    {
        public CliqueTagRequest()
        {
            this.CliqueTagTweetMappings = new HashSet<CliqueTagTweetMapping>();
        }
    
        public int Id { get; set; }
        public string Tag { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public int Status { get; set; }
        public string Location { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual ICollection<CliqueTagTweetMapping> CliqueTagTweetMappings { get; set; }
    }
}
