//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliqueDataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ipl_CliqueAnalyzerDB : DbContext
    {
        public ipl_CliqueAnalyzerDB()
            : base("name=ipl_CliqueAnalyzerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CliqueTagRequest> CliqueTagRequests { get; set; }
        public virtual DbSet<CliqueTagTweetMapping> CliqueTagTweetMappings { get; set; }
        public virtual DbSet<CliqueTweet> CliqueTweets { get; set; }
        public virtual DbSet<CliqueLocationEvent> CliqueLocationEvents { get; set; }
        public virtual DbSet<CliqueLocationRequest> CliqueLocationRequests { get; set; }
        public virtual DbSet<CliqueLocationTweet> CliqueLocationTweets { get; set; }
        public virtual DbSet<CliqueEvent> CliqueEvents { get; set; }
        public virtual DbSet<CliqueExternalScore> CliqueExternalScores { get; set; }
    }
}
