//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliqueDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueLocationEvent
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int EventId { get; set; }
    
        public virtual CliqueLocationRequest CliqueLocationRequest { get; set; }
        public virtual CliqueEvent CliqueEvent { get; set; }
    }
}
