//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliqueDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueTweet
    {
        public CliqueTweet()
        {
            this.CliqueTagTweetMappings = new HashSet<CliqueTagTweetMapping>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string PostedBy { get; set; }
        public string PostedAt { get; set; }
        public Nullable<double> Score { get; set; }
        public System.DateTime AddedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string ProfileImageURL { get; set; }
        public string TweetIdStr { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<CliqueTagTweetMapping> CliqueTagTweetMappings { get; set; }
    }
}
