//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliqueDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CliqueExternalScore
    {
        public int Id { get; set; }
        public string Pincode { get; set; }
        public double CrimeScore { get; set; }
        public double UnemploymentScore { get; set; }
    }
}
